include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    flutter_style_todos: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    avoid_print: false

analyzer:
  errors:
    invalid_override_of_non_virtual_member: error
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
