name: isolated_logic
description: Bring up your business logic (and state management) into separated isolate
version: 0.0.1
repository: https://github.com/kitsuniru/isolated_logic
issue_tracker: https://github.com/kitsuniru/isolated_logic/issues
homepage: https://github.com/kitsuniru/isolated_logic

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  async: ^2.11.0
  collection: ^1.17.2
  meta: ^1.10.0
  stream_transform: ^2.1.0

dev_dependencies:
  very_good_analysis: ^5.1.0
