name: isolated_logic
description: Bring up your business logic (and state management) into separated isolate
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  async: ^2.11.0
  collection: ^1.17.2
  meta: ^1.10.0
  stream_transform: ^2.1.0
